"""SAML pre-auth single-use login transaction store (F-014 STEP 5).

Revision ID: 0017
Revises: 0016
Create Date: 2026-06-21

ADR-0017 §6 (D5) requires server-side, single-use state for the SP-initiated SAML
flow (Fork 4 = SP-initiated only, signed assertion required):
  * `request_id`    — the AuthnRequest ID generated by the SP at login-start. The
                      ACS rejects any SAMLResponse whose `InResponseTo` != this id,
                      which defeats replay AND IdP-initiated-response injection
                      (vector 7). It is the only handle the flow round-trips.
  * `tenant_id` / `idp_config_id` — the R1 tenant binding: the tenant is the OWNER
                      of the matched SAML idp_config, recorded HERE at login-start,
                      never read from the assertion (vector 2).

WHY THIS TABLE IS GLOBAL (no RLS, privileged-session only):
  The SAML login + ACS endpoints are UNAUTHENTICATED — the signed assertion IS the
  auth — so at login-start there is NO operator/tenant session context yet (the RLS
  GUC is unset). This table is therefore keyed by the unguessable AuthnRequest
  `request_id` and binds `tenant_id` as a column, mirroring the global
  `oidc_login_transaction` (migration 0016) and `tenants` registry pattern: it is
  written and read ONLY through get_privileged_session() (owner role). sentinel_app
  receives NO grant on it — the NOBYPASSRLS app role never touches the pre-auth
  store.

Single-use (replay rejection, vector 7): `consumed_at` is set atomically on the
FIRST consume of a row (one UPDATE ... WHERE consumed_at IS NULL AND not expired
... RETURNING); a second consume of the same `request_id` matches nothing and
returns None. Expired rows (`expires_at < now()`) are likewise non-consumable
(fail-closed) and are opportunistically deleted.

Reversible: downgrade() drops the table and its index. Loss-free — pre-F-014 data
is untouched and the table holds only short-lived (<=TTL) pre-auth handles.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0017"
down_revision: Union[str, None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "saml_login_transaction"
_EXPIRES_INDEX = "ix_saml_login_transaction_expires_at"


def upgrade() -> None:
    op.create_table(
        _TABLE,
        # `request_id` is the SP-generated AuthnRequest ID AND the primary key — the
        # only value the flow round-trips (the IdP echoes it as InResponseTo).
        # python3-saml generates an "ONELOGIN_<40 hex>" id (~49 chars); 64 leaves
        # head-room.
        sa.Column("request_id", sa.String(64), primary_key=True),
        # The R1 tenant binding — the SAML idp_config OWNER, recorded at login-start.
        sa.Column("tenant_id", sa.String(64), nullable=False),
        sa.Column("idp_config_id", sa.String(64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # Hard TTL; a row past expires_at is non-consumable (fail-closed).
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        # Set once, atomically, on first consume — single-use replay guard (vector 7).
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # Index supports the opportunistic expired-row cleanup sweep.
    op.create_index(_EXPIRES_INDEX, _TABLE, ["expires_at"])

    # No GRANT to sentinel_app and no RLS policy: this pre-auth store is global and
    # is touched ONLY by the privileged (owner) session, which owns the table by
    # default. The NOBYPASSRLS app role must never read or write it.


def downgrade() -> None:
    op.drop_index(_EXPIRES_INDEX, table_name=_TABLE)
    op.drop_table(_TABLE)
