{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sentinel.minioFullname" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
  {{- if .Values.minio.storageClassName }}
  storageClassName: {{ .Values.minio.storageClassName | quote }}
  {{- end }}
{{- end }}
