{{- if .Values.otelCollector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.otelCollectorFullname" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
{{- end }}
