{{- if .Values.redis.bundled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.redisFullname" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
