{{- if .Values.postgres.bundled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rendly.postgresFullname" . }}
  labels:
    {{- include "rendly.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName | quote }}
  {{- end }}
{{- end }}
